### ISSUE TITLE
Status errors without swap

### ISSUE THREAD

**Issue by jhakonen** [andresgongora/synth-shell#140]
I don't have swap partition in my system, and I get this:

[Image removed by andresgongora, to protect your privacy]

Notice the "N/A{fc_none}" at Swap and the errors at end.

The {fc_none} seems to come because there is no $ at front of it when it is printed out in the printMonitorSwap() function. Should the N/A be horizontally aligned that way, directly attached to the Swap text?

The error lines at end are coming from printHogsMemory() function.
The divide by zero comes from line 1003: local percent=$(bc <<< "$current*100/$max")
And the second error comes from line 1005: if [ $percent -gt $crit_swap_percent ]; then

With a bit of debug logging, here's what the variables contain:
```bash
echo "SWAP INFO: '$swap_info'"
echo "CURRENT: '$current'"
echo "MAX: '$max'"
echo "PERCENT: '$percent'"
```
```
SWAP INFO: 'Swap:             0           0           0'
CURRENT: '0'
MAX: '0'
PERCENT: ''
```

**Comment by andresgongora** [comment]
I will add some extra checks to only print the swap info if there is any swap, or print N/A otherwise (without the trailing error message). I think I can have it by tomorrow.

For now, please edit your user configuration file `~/.config/synth-shell/status.config`. Search for the `print_info` part and delete `SWAP_MON` (probably line 88 or so). After that the error message should be gone once you open a new terminal. Please report if you have any troubles afterwards.

**Comment by andresgongora** [comment]
Fixed in c1e5c37a2a08ee6fab38eab12ab404d76a361b38. I'll soon tidy the repo up and dare a big `master` merge. But for now all fixes and changes are going into the `develop` branch because they are not critical.

Anyway, the issue should be gone. With the info you provided me I located the error in less than 10 seconds: it seems I started to write a special conditions in case the system had no swap (like in your case) but never got to finish/test it. 

Thanks a lot for your feedback! It helps a lot!

PS: If the bug persists, please open this issue again, or if you have any feature request, feel free to open a new one. Otherwise, enjoy your awesome terminal :D

**Comment by jhakonen** [comment]
Hey, I tried the develop branch just now (HEAD is at c1e5c37). The Swap entry looks much better now :)

Unfortunately the error messages didn't disappear, I'm still getting these:
```
Runtime error (func=(main), adr=9): Divide by zero
bash: [: -gt: unary operator expected
```
I don't seem to have enough permissions to open the issue again (missing the "Reopen issue" button).

**Comment by andresgongora** [comment]
Ok. I'm super sleepy right now hehehe but I think I see the problem.

```
	local message="Swap"
	local units="MB"
	local swap_info=$('free' -m | tail -n 1)
	local current=$(echo "$swap_info" | awk '{SWAP=($3)} END {printf SWAP}')
	local max=$(echo "$swap_info" | awk '{SWAP=($2)} END {printf SWAP}')
```
This chunk of code checks how much swap you have. Usually, `max` will contain the maximum value of it. Then, in 

```
if [ "$max" -eq "0" ]; then
```

I check if its greater than zero to avoid some divide by zero issues when printing the monitor. Now, the problem is that this is a patch I wrote and is "good" to protect the monitor from zero values, but real bad at actually checking whether you have any swap. Why? because if there is no swap at all, who knows what `max` will contain. Most likely something related to the RAM by looking at it.

Any way. I'm going to move the "zero-value" protections into `printMonitor`, and do a stand-alone check for swap before proceeding. For that I need your help, as I don't have any sisytem without swap at hand. Would you mind telling me the output you get for `cat /proc/swap`? `/proc/swap` should contain a list of all swap decives on your system, and if I'm not mistaken, it should be empty on yours.

Thanks for the help. I think we can fix this real soon :)

**Comment by jhakonen** [comment]
Hmm, I don't seem to have such a file:
```bash
$ cat /proc/swap
cat: /proc/swap: No such file or directory
```
There's swaps file though which seems to contain only headers:
```
$ ll /proc/swap*
-r--r--r-- 1 root root 0 joulu   4 08:34 /proc/swaps
$ cat /proc/swaps 
Filename				Type		Size	Used	Priority
$ echo "\"$(cat /proc/swaps)\"" 
"Filename				Type		Size	Used	Priority"
```

**Comment by andresgongora** [comment]
My bad, it was `/proc/swaps` all along, with an `s` at the end. But with the output you have sent me I think I've come up with a solution. I've just pushed to `develop`. Would you mind checking if the fix works better now?

**Comment by jhakonen** [comment]
Unfortunately the errors are still coming. No change there.

The divide by zero error is coming from this line:
https://github.com/andresgongora/synth-shell/blob/bd92a6c/synth-shell/status.sh#L1130

**Comment by andresgongora** [comment]
Ok! I think that one is solved too. I hope there are no other places left where I should check for swap partitions. Could you check?? :)
(pushed to bd92a6c )

**Comment by jhakonen** [comment]
yeah, now it seems to be fine. I don't see any errors anymore :)

**Comment by andresgongora** [comment]
Perfect!! I'm glad it worked!!
If the error comes back or anything please let me know (I'm reclosing this issue for now).
I'll probably do some tidy up of the code during the holidays and push our fix to master.
Thanks for your feedback :)
